# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'http://git.thedeer.cn/iosteam/zykjspecs.git'

#use_frameworks!

target 'Demo1' do

pod 'zykjMacro'
pod 'zykjExt'
pod 'zykjUtils'
pod 'MJRefresh', '~> 3.5.0'

end
